default_language_version:
  python: python3

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.108.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.3.8
    hooks:
      - id: checkov
        args: [--quiet, --skip-check, "CKV_AWS_273,CKV_AWS_40"]

  - repo: https://github.com/ansible/ansible-lint
    rev: v26.6.0
    hooks:
      - id: ansible-lint
        language_version: python3
        additional_dependencies:
          - boto3
          - botocore
          - docker
          - kubernetes
        entry: bash -c 'ansible-galaxy collection install -r ansible/requirements.yml && ansible-lint "$@"' --
        files: ^ansible/.*\.(yml|yaml)$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [-d, relaxed]
