version: 0.2

phases:
  install:
    commands:
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.72.0
  pre_build:
    commands:
      - echo "codebuild resolved source version is $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)
      - echo "resolved image tag is $IMAGE_TAG"
  build:
    commands:
      - docker build -t $ECR_REPOSITORY_URL:$IMAGE_TAG app/
  post_build:
    commands:
      - docker push $ECR_REPOSITORY_URL:$IMAGE_TAG
      - trivy image --exit-code 1 --severity CRITICAL --ignorefile .trivyignore --no-progress $ECR_REPOSITORY_URL:$IMAGE_TAG
      - trivy image --format cyclonedx --output sbom-$IMAGE_TAG.json $ECR_REPOSITORY_URL:$IMAGE_TAG
