services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-devsecops:lts-jdk21
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - jenkins_home:/var/jenkins_home
      - maven_repo:/var/jenkins_home/.m2/repository
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PIPELINE_REPO_PATH}:/var/jenkins_home/devsecops-cicd-pipeline:ro
    restart: unless-stopped

  sonarqube:
    image: sonarqube:26.3.0.120487-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus_data:/nexus-data
    restart: unless-stopped

volumes:
  jenkins_home:
  maven_repo:
  sonarqube_data:
  sonarqube_extensions:
  nexus_data:
