services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-devsecops:lts-jdk21
    container_name: jenkins
    user: root
    mem_limit: 3g
    cpus: 2.0
    ports:
      - "8080:8080"
      - "50000:50000"
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true -Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - maven_repo:/var/jenkins_home/.m2/repository
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PIPELINE_REPO_PATH}:/var/jenkins_home/devsecops-cicd-pipeline:ro
      - ./jenkins/casc.yaml:/var/jenkins_home/casc.yaml:ro
      - ./jenkins/job-dsl.groovy:/var/jenkins_home/job-dsl.groovy:ro
    restart: unless-stopped

  sonarqube:
    image: sonarqube:26.3.0.120487-community
    container_name: sonarqube
    mem_limit: 2g
    cpus: 1.5
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    mem_limit: 2g
    cpus: 1.0
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus_data:/nexus-data
    restart: unless-stopped

volumes:
  jenkins_home:
  maven_repo:
  sonarqube_data:
  sonarqube_extensions:
  nexus_data:
