FROM jenkins/jenkins:lts-jdk21

USER root

RUN apt-get update && \
    apt-get install -y \
      curl \
      git \
      maven \
      docker.io && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sLO https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

RUN curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

RUN curl -sLo /usr/local/bin/kind \
    https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64 && \
    chmod +x /usr/local/bin/kind

RUN git config --system --add safe.directory '*'


RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install -y nodejs

RUN npm install -g snyk

RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

RUN curl -sLo gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.21.2/gitleaks_8.21.2_linux_x64.tar.gz && \
    tar -xzf gitleaks.tar.gz gitleaks && \
    mv gitleaks /usr/local/bin/ && \
    rm gitleaks.tar.gz

RUN node --version && npm --version && snyk --version && trivy --version && gitleaks version

USER jenkins
