falcosidekick:
  enabled: true
  config:
    aws:
      region: us-east-1
      accesskeyid: test
      secretaccesskey: test
      sns:
        topicarn: arn:aws:sns:us-east-1:000000000000:devsecops-pipeline-alerts
        minimumpriority: critical
        rawjson: true
