jenkins:
  systemMessage: devsecops pipeline controller
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_USER}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      entries:
        - user:
            name: "${JENKINS_ADMIN_USER}"
            permissions:
              - "Overall/Administer"
        - group:
            name: "authenticated"
            permissions:
              - "Overall/Read"

unclassified:
  location:
    adminAddress: devsecops-pipeline@local
    url: http://localhost:8080/
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
      - name: SonarQube
        serverUrl: http://sonarqube:9000
        credentialsId: sonar-token

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: sonar-token
              secret: ${SONAR_TOKEN}
              description: sonar-token
          - string:
              scope: GLOBAL
              id: snyk-token
              secret: ${SNYK_TOKEN}
              description: snyk-token
          - string:
              scope: GLOBAL
              id: aws-account-id
              secret: ${AWS_ACCOUNT_ID}
              description: aws-account-id
          - aws:
              scope: GLOBAL
              id: aws-jenkins-creds
              accessKey: ${AWS_JENKINS_ACCESS_KEY_ID}
              secretKey: ${AWS_JENKINS_SECRET_ACCESS_KEY}
              description: aws-jenkins-creds

jobs:
  - script: |
      pipelineJob('devsecops-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/UdayKumarChunduru/devsecops-cicd-pipeline.git')
                }
                branch('*/aws')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
